
query products {
  shopInfo: shop {
    name
  }
  
  products: shop {
    products {
      edges {
        node {
          title
          listPrice {
            amount
          }
          categories {
            path
            name
          }
          promotions {
            name
          }
        }
      }
    }
  }
}