
query products {
  shop {
    name
    products {
      edges {
        node {
          title
          listPrice {
            amount
          }
          categories {
            path
            name
          }
          
          promotions {
            name
          }
        }
      }
    }
  }
}
